-- Create events table
CREATE TABLE IF NOT EXISTS events (
  id VARCHAR(36) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  slug VARCHAR(255) NOT NULL UNIQUE,
  description TEXT NOT NULL,
  category ENUM('craft_fair', 'workshop', 'exhibition', 'marketplace', 'conference', 'networking', 'other') NOT NULL,
  event_type ENUM('physical', 'virtual', 'hybrid') NOT NULL,
  location VARCHAR(500),
  virtual_link VARCHAR(500),
  start_date DATETIME NOT NULL,
  end_date DATETIME NOT NULL,
  registration_deadline DATETIME,
  max_capacity INT,
  current_participants INT DEFAULT 0,
  requirements TEXT,
  banner_image VARCHAR(500),
  status ENUM('draft', 'published', 'ongoing', 'completed', 'cancelled') DEFAULT 'draft',
  visibility ENUM('public', 'invite_only', 'private') DEFAULT 'public',
  organizer_id VARCHAR(36) NOT NULL,
  tags JSON,
  schedule JSON,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (organizer_id) REFERENCES vendors(id) ON DELETE CASCADE,
  INDEX idx_organizer_id (organizer_id),
  INDEX idx_status (status),
  INDEX idx_category (category),
  INDEX idx_start_date (start_date),
  INDEX idx_visibility (visibility)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Create event_registrations table
CREATE TABLE IF NOT EXISTS event_registrations (
  id VARCHAR(36) PRIMARY KEY,
  event_id VARCHAR(36) NOT NULL,
  vendor_id VARCHAR(36) NOT NULL,
  status ENUM('pending', 'confirmed', 'waitlist', 'cancelled', 'attended') DEFAULT 'pending',
  registration_date DATETIME NOT NULL,
  notes TEXT,
  rating INT CHECK (rating >= 1 AND rating <= 5),
  feedback TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE,
  FOREIGN KEY (vendor_id) REFERENCES vendors(id) ON DELETE CASCADE,
  UNIQUE KEY unique_event_vendor (event_id, vendor_id),
  INDEX idx_vendor_id (vendor_id),
  INDEX idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
